### ISSUE TITLE
Physical view is not presenting 

### ISSUE THREAD

**Issue by JesseMonteiro** [tiki/capture-receipt-ios#22]
### Reason

The microblink physical view is not presenting

### Description

The follow error code is present in the console log.

Attempt to present <BRNewStaticScanViewController: 0x10f83ac00> on <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x10c034e00> (from <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x10c034e00>) which is already presenting <_TtGC7SwiftUI19UIHostingControllerV11TikiRewards10HomeScreen_: 0x10c02f400>.

### Success Criteria

- [ ] Present the microblink physical scan view

**Comment by ricardobrg** [comment]
duplicate https://github.com/tiki/apps-rewards-ios/issues/63
